In [1]:
import pandas as pd

df = pd.read_csv('balon_de_oro.csv')

print("¡Datos cargados con éxito! Aquí tienes una vista previa:")
display(df.head())

¡Datos cargados con éxito! Aquí tienes una vista previa:

  HISTÓRICO TOP 5 BALÓN DE ORO (1956 - 1999);;;;;;;;
0                                           ;;;;;;;;
1                                           ;;;;;;;;
2  Año;Posición;Jugador;Club(s);Nacionalidad;Cham...
3  1956;1;Stanley Matthews;Blackpool;Inglaterra;N...
4  1956;2;Alfredo Di Stéfano;Real Madrid;España;S...

In [2]:
import altair as alt

chart = alt.Chart(df).mark_circle(size=100).encode(
    x=alt.X('Año:O', title='Año de premiación'),
    y=alt.Y('liga:N', title='Liga del Jugador'),
    color=alt.Color('club:N', legend=alt.Legend(title="Club")),
    tooltip=['Año', 'jugador', 'club', 'liga']
).properties(
    title='Evolución del Balón de Oro: Relación de Ligas y Clubes (1956-2025)',
    width=700,
    height=450
).interactive()

chart.display()

ValueError: Unable to determine data type for the field "Año"; verify that the field name is not misspelled. If you are referencing a field from a transform, also confirm that the data type is specified correctly.

alt.Chart(...)

In [3]:
print(df.columns)

Index(['HISTÓRICO TOP 5 BALÓN DE ORO (1956 - 1999);;;;;;;;'], dtype='object')

In [4]:
import pandas as pd

df = pd.read_csv('balon_de_oro.csv', header=1)

print("¡Listo! Las columnas reales son:")
print(df.columns.tolist())

display(df.head())

¡Listo! Las columnas reales son:
[';;;;;;;;']

                                            ;;;;;;;;
0                                           ;;;;;;;;
1  Año;Posición;Jugador;Club(s);Nacionalidad;Cham...
2  1956;1;Stanley Matthews;Blackpool;Inglaterra;N...
3  1956;2;Alfredo Di Stéfano;Real Madrid;España;S...
4  1956;3;Raymond Kopa;Real Madrid / Stade de Rei...

In [5]:
import pandas as pd

with open('balon_de_oro.csv', 'r', encoding='utf-8', errors='ignore') as f:
    lines = f.readlines()

header_idx = 0
for i, line in enumerate(lines):
    if 'Año' in line or 'Jugador' in line:
        header_idx = i
        break

df = pd.read_csv('balon_de_oro.csv', sep=';', skiprows=header_idx)

df.columns = df.columns.str.strip()

print("¡ÉXITO! Las columnas de tu tabla ahora son:")
print(df.columns.tolist())

display(df.head())

¡ÉXITO! Las columnas de tu tabla ahora son:
['Año', 'Posición', 'Jugador', 'Club(s)', 'Nacionalidad', 'Champions League', 'Liga Nacional', 'Mundial (Selección y Resultado)', 'Torneo Continental (Euro / Copa América / África / Asia)']

,Año,Posición,Jugador,Club(s),Nacionalidad,Champions League,Liga Nacional,Mundial (Selección y Resultado),Torneo Continental (Euro / Copa América / África / Asia)
0,1956,1,Stanley Matthews,Blackpool,Inglaterra,No,No,NaN,NaN
1,1956,2,Alfredo Di Stéfano,Real Madrid,España,Sí,No,NaN,NaN
2,1956,3,Raymond Kopa,Real Madrid / Stade de Reims,Francia,No,Sí (Ligue 1),NaN,NaN
3,1956,4,Ferenc Puskás,Budapest Honvéd,Hungría,No,No,NaN,NaN
4,1956,5,Lev Yashin,Dynamo Moscú,Unión Soviética,No,No,NaN,NaN

In [6]:
import altair as alt
import pandas as pd

df['Gano_Champions'] = df['Champions League'].astype(str).str.contains('Sí|Si|sí|si', case=False, na=False)

conteo = df['Gano_Champions'].value_counts().reset_index()
conteo.columns = ['Champions', 'Cantidad']
conteo['Champions'] = conteo['Champions'].replace({True: 'Ganaron Champions League', False: 'No ganaron Champions League'})

conteo['Porcentaje'] = (conteo['Cantidad'] / conteo['Cantidad'].sum()) * 100

chart = alt.Chart(conteo).mark_bar(cornerRadiusTopLeft=8, cornerRadiusTopRight=8).encode(
    x=alt.X('Champions:N', title='Condición', sort='-y'),
    y=alt.Y('Porcentaje:Q', title='Porcentaje (%) del Top 5 del Balón de Oro'),
    color=alt.Color('Champions:N', legend=None, scale=alt.Scale(range=['#2b5c8f', '#b0c4de'])),
    tooltip=['Champions', 'Cantidad', alt.Tooltip('Porcentaje:Q', format='.1f', title='Porcentaje (%)')]
).properties(
    title='Impacto de la Champions League en el Top 5 del Balón de Oro (1956-2025)',
    width=500,
    height=400
).interactive()

chart.display()

alt.Chart(...)

In [7]:
import altair as alt
import pandas as pd

df['Posición_limpia'] = pd.to_numeric(
    df['Posición'].astype(str).str.extract(r'(\d+)')[0], errors='coerce'
)
df_ganadores = df[df['Posición_limpia'] == 1].copy()

df_ganadores['Gano_Champions'] = (
    df_ganadores['Champions League']
    .astype(str)
    .str.contains('Sí|Si|sí|si', case=False, na=False)
)

conteo = df_ganadores['Gano_Champions'].value_counts().reset_index()
conteo.columns = ['Champions', 'Cantidad']
conteo['Champions'] = conteo['Champions'].replace(
    {True: 'Ganaron Champions League', False: 'No ganaron Champions League'}
)

total_ganadores = conteo['Cantidad'].sum()
conteo['Porcentaje'] = (conteo['Cantidad'] / total_ganadores) * 100

print(f'Total de ganadores analizados: {total_ganadores}')
display(conteo)

chart = (
    alt.Chart(conteo)
    .mark_bar(size=60)
    .encode(
        x=alt.X(
            'Champions:N',
            title='Condición del Ganador del Balón de Oro',
            sort='-y',
        ),
        y=alt.Y(
            'Porcentaje:Q', title='Porcentaje (%) de los Ganadores del Balón de Oro'
        ),
        color=alt.Color('Champions:N', legend=None),
        tooltip=['Champions', 'Cantidad', alt.Tooltip('Porcentaje:Q', format='.1f', title='Porcentaje (%)')]
    )
    .properties(
        title=(
            'Porcentaje de Ganadores del Balón de Oro que conquistaron la'
            ' Champions League'
        ),
        width=450,
        height=350,
    )
    .interactive()
)

chart.display()

Total de ganadores analizados: 44

                     Champions  Cantidad  Porcentaje
0  No ganaron Champions League        34   77.272727
1     Ganaron Champions League        10   22.727273

alt.Chart(...)

In [8]:
import altair as alt
import pandas as pd

df['Año_num'] = pd.to_numeric(df['Año'].astype(str).str.extract(r'(\d+)')[0], errors='coerce')
df['Posición_limpia'] = pd.to_numeric(df['Posición'].astype(str).str.extract(r'(\d+)')[0], errors='coerce')

df_filtrado = df[(df['Posición_limpia'] == 1) & (df['Año_num'] >= 1956) & (df['Año_num'] <= 1999)].copy()

df_filtrado['Gano_Champions'] = df_filtrado['Champions League'].astype(str).str.contains('Sí|Si|sí|si', case=False, na=False)

conteo = df_filtrado['Gano_Champions'].value_counts().reset_index()
conteo.columns = ['Champions', 'Cantidad']
conteo['Champions'] = conteo['Champions'].replace({True: 'Ganaron Champions League', False: 'No ganaron Champions League'})

total_ganadores = conteo['Cantidad'].sum()
conteo['Porcentaje'] = (conteo['Cantidad'] / total_ganadores) * 100

print(f"Total de ganadores analizados entre 1956 y 1999: {total_ganadores}")
display(conteo)

base = alt.Chart(conteo).encode(
    theta=alt.Theta(field="Cantidad", type="quantitative"),
    color=alt.Color(field="Champions", type="nominal", title="Condición del Ganador")
)

pie = base.mark_arc(outerRadius=130, innerRadius=65).encode(
    tooltip=['Champions', 'Cantidad', alt.Tooltip('Porcentaje:Q', format='.1f', title='Porcentaje (%)')]
)

chart_pie = pie.properties(
    title='Ganadores del Balón de Oro (1956-1999): Relación con la Champions League',
    width=500,
    height=400
).interactive()

chart_pie.display()

Total de ganadores analizados entre 1956 y 1999: 44

                     Champions  Cantidad  Porcentaje
0  No ganaron Champions League        34   77.272727
1     Ganaron Champions League        10   22.727273

alt.Chart(...)

In [9]:
chart_pie.save('vis_01.html')
print("¡Gráfico de torta guardado como 'vis_01.html'! Descárgalo desde la carpeta de la izquierda en Colab.")

¡Gráfico de torta guardado como 'vis_01.html'! Descárgalo desde la carpeta de la izquierda en Colab.

In [10]:
import altair as alt
import pandas as pd

df['Año_num'] = pd.to_numeric(df['Año'].astype(str).str.extract(r'(\d+)')[0], errors='coerce')
df['Posición_limpia'] = pd.to_numeric(df['Posición'].astype(str).str.extract(r'(\d+)')[0], errors='coerce')

df_filtrado = df[(df['Posición_limpia'] == 1) & (df['Año_num'] >= 1956) & (df['Año_num'] <= 1999)].copy()

def gano_seleccion(row):
    mundial = str(row.get('Mundial (Selección y Resultado)', ''))
    continental = str(row.get('Torneo Continental (Euro / Copa América / África / Asia)', ''))
    texto_total = (mundial + " " + continental).lower()

    if 'campeon' in texto_total or 'campeón' in texto_total or '1' in texto_total or 'sí' in texto_total or 'si' in texto_total:
        if 'no participo' not in texto_total and 'eliminado' not in texto_total:
            return True
    return False

df_filtrado['Gano_Seleccion'] = df_filtrado.apply(gano_seleccion, axis=1)

conteo_sel = df_filtrado['Gano_Seleccion'].value_counts().reset_index()
conteo_sel.columns = ['Seleccion', 'Cantidad']
conteo_sel['Seleccion'] = conteo_sel['Seleccion'].replace({True: 'Ganaron Título con Selección', False: 'No ganaron Título con Selección'})

total_ganadores = conteo_sel['Cantidad'].sum()
conteo_sel['Porcentaje'] = (conteo_sel['Cantidad'] / total_ganadores) * 100

print(f"Total de ganadores analizados (1956-1999): {total_ganadores}")
display(conteo_sel)

base_sel = alt.Chart(conteo_sel).encode(
    theta=alt.Theta(field="Cantidad", type="quantitative"),
    color=alt.Color(field="Seleccion", type="nominal", title="Condición de Selección")
)

pie_sel = base_sel.mark_arc(outerRadius=130, innerRadius=65).encode(
    tooltip=['Seleccion', 'Cantidad', alt.Tooltip('Porcentaje:Q', format='.1f', title='Porcentaje (%)')]
)

chart_pie_sel = pie_sel.properties(
    title='Ganadores del Balón de Oro (1956-1999): Peso de los Títulos de Selección',
    width=500,
    height=400
).interactive()

chart_pie_sel.display()

Total de ganadores analizados (1956-1999): 44

                         Seleccion  Cantidad  Porcentaje
0     Ganaron Título con Selección        23   52.272727
1  No ganaron Título con Selección        21   47.727273

alt.Chart(...)

In [11]:
import altair as alt
import pandas as pd

df['Año_num'] = pd.to_numeric(df['Año'].astype(str).str.extract(r'(\d+)')[0], errors='coerce')
df['Posición_limpia'] = pd.to_numeric(df['Posición'].astype(str).str.extract(r'(\d+)')[0], errors='coerce')

df_filtrado = df[(df['Posición_limpia'] == 1) & (df['Año_num'] >= 1956) & (df['Año_num'] <= 1999)].copy()

def gano_titulo_seleccion(row):
    mundial = str(row.get('Mundial (Selección y Resultado)', '')).lower()
    continental = str(row.get('Torneo Continental (Euro / Copa América / África / Asia)', '')).lower()

    es_campeon = ('campeón' in mundial or 'campeon' in mundial or
                  'campeón' in continental or 'campeon' in continental)

    return es_campeon

df_filtrado['Gano_Seleccion_Real'] = df_filtrado.apply(gano_titulo_seleccion, axis=1)

conteo_sel = df_filtrado['Gano_Seleccion_Real'].value_counts().reset_index()
conteo_sel.columns = ['Seleccion', 'Cantidad']
conteo_sel['Seleccion'] = conteo_sel['Seleccion'].replace({
    True: 'Campeones con Selección (Mundial/Euro/Copa)',
    False: 'Sin Título de Selección en ese año'
})

total_ganadores = conteo_sel['Cantidad'].sum()
conteo_sel['Porcentaje'] = (conteo_sel['Cantidad'] / total_ganadores) * 100

print(f"Total de ganadores analizados (1956-1999): {total_ganadores}")
display(conteo_sel)

base_sel = alt.Chart(conteo_sel).encode(
    theta=alt.Theta(field="Cantidad", type="quantitative"),
    color=alt.Color(field="Seleccion", type="nominal", title="Condición de Selección")
)

pie_sel = base_sel.mark_arc(outerRadius=130, innerRadius=65).encode(
    tooltip=['Seleccion', 'Cantidad', alt.Tooltip('Porcentaje:Q', format='.1f', title='Porcentaje (%)')]
)

chart_pie_sel = pie_sel.properties(
    title='Ganadores del Balón de Oro (1956-1999): Títulos reales con la Selección',
    width=500,
    height=400
).interactive()

chart_pie_sel.display()

Total de ganadores analizados (1956-1999): 44

                                     Seleccion  Cantidad  Porcentaje
0           Sin Título de Selección en ese año        30   68.181818
1  Campeones con Selección (Mundial/Euro/Copa)        14   31.818182

alt.Chart(...)

In [12]:
import altair as alt
import pandas as pd

df['Año_num'] = pd.to_numeric(df['Año'].astype(str).str.extract(r'(\d+)')[0], errors='coerce')
df['Posición_limpia'] = pd.to_numeric(df['Posición'].astype(str).str.extract(r'(\d+)')[0], errors='coerce')

df_filtrado = df[(df['Posición_limpia'] == 1) & (df['Año_num'] >= 1956) & (df['Año_num'] <= 1999)].copy()

def gano_titulo_seleccion_estricto(row):
    mundial = str(row.get('Mundial (Selección y Resultado)', '')).lower()
    continental = str(row.get('Torneo Continental (Euro / Copa América / África / Asia)', '')).lower()

    texto_total = mundial + " " + continental

    if 'subcampeón' in texto_total or 'subcampeon' in texto_total:
        return False

    es_campeon = ('campeón' in texto_total or 'campeon' in texto_total)

    return es_campeon

df_filtrado['Gano_Seleccion_Estricto'] = df_filtrado.apply(gano_titulo_seleccion_estricto, axis=1)

conteo_sel = df_filtrado['Gano_Seleccion_Estricto'].value_counts().reset_index()
conteo_sel.columns = ['Seleccion', 'Cantidad']
conteo_sel['Seleccion'] = conteo_sel['Seleccion'].replace({
    True: 'Campeones con Selección (Mundial/Euro/Copa)',
    False: 'Sin Título de Selección en ese año'
})

total_ganadores = conteo_sel['Cantidad'].sum()
conteo_sel['Porcentaje'] = (conteo_sel['Cantidad'] / total_ganadores) * 100

print(f"Total de ganadores analizados (1956-1999): {total_ganadores}")
display(conteo_sel)

base_sel = alt.Chart(conteo_sel).encode(
    theta=alt.Theta(field="Cantidad", type="quantitative"),
    color=alt.Color(field="Seleccion", type="nominal", title="Condición de Selección")
)

pie_sel = base_sel.mark_arc(outerRadius=130, innerRadius=65).encode(
    tooltip=['Seleccion', 'Cantidad', alt.Tooltip('Porcentaje:Q', format='.1f', title='Porcentaje (%)')]
)

chart_pie_sel = pie_sel.properties(
    title='Ganadores del Balón de Oro (1956-1999): Títulos reales con la Selección',
    width=500,
    height=400
).interactive()

chart_pie_sel.display()

Total de ganadores analizados (1956-1999): 44

                                     Seleccion  Cantidad  Porcentaje
0           Sin Título de Selección en ese año        33        75.0
1  Campeones con Selección (Mundial/Euro/Copa)        11        25.0

alt.Chart(...)

In [13]:
chart_pie_sel.save('vis_02.html')
print("¡Gráfico de selección corregido guardado como 'vis_02.html'! Descárgalo desde la izquierda.")

¡Gráfico de selección corregido guardado como 'vis_02.html'! Descárgalo desde la izquierda.